//SCOPE

{
  {
    //CHILD BLOCK
    let a = 10;
    //console.log(a);
  }
}
console.log(a);

//A VARIABLE WILL ONLY BE KNOWN WITHIN ITS BLOCK FROM THE LINE WHERE IT IS DEFINED/WRITTEN.

// WHEN A VARIABLE IS BLOCK, FIRST ITLL BE SEARCHED IN ITS OWN BLOCK. IF
// VARIABLE IS NOT FOUND IN SAIDCSSLayerBlockRule, THEN ITLL SEARCH IN PARENT BLOCK.

{
  let a = 1;
  {
    let a = 10;
    console.log(a);
  }
  console.log(a);
}
//A VARIABLE CAN NOT BE DEFINED TWICE (REDEFINED)
//  IN THE SAME BLOCK. BUT WE CAN REDEFINE THE SAME VARIABLE IN DIFFERENT BLOCK.
